services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    container_name: finance_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - "backend/.env"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_finance
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
